(print "----------------------------------------\n")
(print "test build-in math functions\n")
(print "----------------------------------------\n")

(run-test "test-add-1" (->
    (= 3 (+ 1 2))))

(run-test "test-add-2" (->
    (= 3 (+ -1 4))))

(run-test "test-add-3" (->
    (= -3 (+ 1 -4))))

(run-test "test-add-4" (->
    (= -5 (+ -2 -3))))

(run-test "test-sub-1" (->
    (= 3 (- 5 2))))

(run-test "test-sub-2" (->
    (= -1 (- 5 6))))

(run-test "test-sub-3" (->
    (= -11 (- -5 6))))

(run-test "test-sub-4" (->
    (= 1 (- -5 -6))))

(run-test "test-mul-1" (->
    (= 6 (* 2 3))))

(run-test "test-mul-2" (->
    (= -6 (* -2 3))))

(run-test "test-mul-3" (->
    (= 6 (* -2 -3))))

(run-test "test-div-1" (->
    (= 3 (/ 6 2))))

(run-test "test-div-2" (->
    (= 2 (/ 8 3 ))))

(run-test "test-div-3" (->
    (= 0 (/ 4 8 ))))

(run-test "test-div-4" (->
    (= -3 (/ -6 2))))

(run-test "test-div-5" (->
    (= 3 (/ -6 -2 ))))

(run-test "test-div-6" (->
    (= 0 (/ 0 4 ))))

(run-test "test-mod-1" (->
    (= 0 (mod 4 2 ))))

(run-test "test-mod-2" (->
    (= 2 (mod 6 4 ))))

(run-test "test-mod-3" (->
    (= 2 (mod 2 4 ))))

