#!/bin/bash

mkdir -p bin

gcc -Wall -Wextra -o bin/donkey \
    src/main.c \
    src/list.c \
    src/tokenize.c \
    src/parse.c \
    src/read.c \
    src/resolve.c \
    src/stack.c \
    src/buildins/compare.c \
    src/buildins/debug.c \
    src/buildins/io.c \
    src/buildins/list.c \
    src/buildins/logic.c \
    src/buildins/math.c \
    src/buildins/misc.c \
    src/buildins/typecheck.c \
    src/buildins/utils.c

