(print "----------------------------------------\n")
(print "test lib/iterate.dl\n")
(print "----------------------------------------\n")

(run-test "filter-1" (->
    (equal?
        (filter
            (-> x (> x 5))
            (list 3 4 5 6 7 8))
        (list 6 7 8))))

(run-test "filter-2" (->
    (equal?
        (filter
            (-> x (> x 5))
            (list 2))
        (list))))

(run-test "filter-3" (->
    (equal?
        (filter
            (-> x (> x 5))
            (list))
        (list))))

(run-test "filter-4" (->
    (equal?
        (filter
            (-> x (str? x))
            (list 2 (list 8 9) "foo" 4))
        (list "foo"))))

(run-test "map-1" (->
    (equal?
        (map
            (-> x (* x x))
            (list 1 2 3 4))
        (list 1 4 9 16))))

(run-test "map-2" (->
    (equal?
        (map
            (-> x (* x x))
            (list))
        (list))))

(run-test "map-3" (->
    (equal?
        (map
            (-> x (list x))
            (list 1 2))
        (list (list 1) (list 2)))))

(run-test "reduce-1" (->
    (= 10 (reduce
            (-> acc x (+ acc x))
            (list 1 2 3 4)
            0))))

(run-test "reduce-1" (->
    (= 42 (reduce
            (-> acc x (+ acc x))
            (list)
            42))))